apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: circuit-breaker-servicex
spec:
  # host: servicex-service.default.svc.cluster.local
  host: servicex-service
  trafficPolicy:
    outlierDetection: # Circuit Breaker
      # consecutive5xxErrors: 20   # 500, 501, 502, 503, 504, 505
      consecutiveGatewayErrors: 10 # 502, 503, 504
      interval: 20s
      baseEjectionTime: 30s # 60s 120s 240s 480s 960s
      maxEjectionPercent: 100 # 100% of pods
